config/routes.rb
TheIguanas::Application.routes.draw do
  root :to => "iguanas#index"

  resources :iguanas, :except => [:destroy]
  resources :users, :only => [:new, :create, :show]
  resources :sessions, :only => [:new, :create, :index, :destroy]

  resources :iguana_house_cleaning_requests, :only => [:new, :create] do
    member do
      post :approve, :to => "iguana_house_cleaning_requests#approve"
      post :deny, :to => "iguana_house_cleaning_requests#deny"
    end
  end

end

app/models/iguana.rb
# == Schema Information
#
# Table name: iguanas
#
#  id         :integer          not null, primary key
#  age        :integer          not null
#  birth_date :date             not null
#  color      :string(255)      not null
#  name       :string(255)      not null
#  sex        :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#

class Iguana < ActiveRecord::Base
  COLORS = %w(aqua green dark_blue brown purple)

  attr_accessible :age, :birth_date, :name, :color, :sex

  validates :age, :birth_date, :name, :color, :sex, :presence => :true
  validates :color, :inclusion => COLORS
  validates :age, :numericality => :true
  validates :sex, :inclusion => ["M", "F"]

  has_many :iguana_house_cleaning_requests, :dependent => :destroy
  belongs_to(:owner,
    :primary_key => :id,
    :foreign_key => :user_id,
    :class_name => "User"
    )

end

app/controllers/iguanas_controller.rb
class IguanasController < ApplicationController
  before_filter :require_current_user!, :except => [:index, :show]
  before_filter :require_owner, :only => [:edit, :update]

  def index
    @iguanas = Iguana.all
    render :index
  end

  def create
    @iguana = Iguana.new(params[:iguana])
    @iguana.user_id = @current_user.id
    if @iguana.save
      redirect_to iguana_url(@iguana)
    else
      @errors = @iguana.errors.full_messages
      render :new
    end
  end

  def edit
    @iguana = Iguana.find(params[:id])
    render :edit
  end

  def new
    @iguana = Iguana.new
    render :new
  end

  def show
    @iguana = Iguana.find(params[:id])
    @requests = @iguana.iguana_house_cleaning_requests.order('start_date')
    render :show
  end

  def update
    @iguana = Iguana.find(params[:id])
    if @iguana.update_attributes(params[:iguana])
      redirect_to iguana_url(@iguana)
    else
      @errors = @iguana.errors.full_messages
      render :edit
    end
  end

  private

  def require_owner
    unless is_owner?
      flash[:notices] = ["You can only edit your own iguanas"]
      redirect_to iguanas_url
    end
  end


end

app/helpers/iguanas_helper.rb
module IguanasHelper
  def is_owner?
    @is_owner = (current_user.id == Iguana.find(params[:id]).user_id) if @is_owner.nil?
    @is_owner
  end
end

app/views/iguanas/_form.html.erb
<% unless @errors.nil?%>
	<ul><% @errors.each do |error|%>
		<li><%= error%></li>
	<%end%>
	</ul>
<%end%>

<% action_url = (action == :edit) ? iguana_url(@iguana) : iguanas_url%>
<% submit_value = (action == :edit) ? "UPDATE THE IGUANA" : "CREATE THE IGUANA"%>

<form action=<%=action_url%> method = "POST">
	<% if @iguana.persisted? %>
		<input type="hidden" name="_method" value="PUT">
	<% end %>

	<label for="iguana_name">NAME</label>
	<input type="text" name="iguana[name]" id="iguana_name" value=<%= @iguana.name %>>
	<br>
	<label for="iguana_color">COLOR</label>
	<select name="iguana[color]" id="iguana_color">
		<% if action == :new %>
		<option value="" selected></option>
		<% end %>
		<% Iguana::COLORS.each do |color|%>
		<option value="<%= color %>"
				<%= "selected" if @iguana && @iguana.color == color%> >
				<%= color.upcase%>
		</option>
		<% end %>
	</select>
	<br>
	<label for="iguana_bdate">DATE OF BIRTH</label>
	<input type="date" name="iguana[birth_date]" id="iguana_bdate"
			value=<%= @iguana.birth_date %>>
	<br>
	<label for="iguana_age">AGE</label>
	<input type="text" name="iguana[age]" id="iguana_age"
			value=<%= @iguana.age %>>
	<br>
	<label for="iguana_sex">SEX</label>
	<select name="iguana[sex]" id="iguana_sex">
		<option value="M" <%= "selected" if @iguana.sex == "M"%>>M</option>
		<option value="F" <%= "selected" if @iguana.sex == "F"%>>F</option>
	</select>
	<br>

	<input type="submit" value="UPDATE THE IGUANA">
</form>

app/views/iguanas/edit.html.erb
<h2>EDIT THE IGUANA</h2>

<% unless @errors.nil?%>
	<ul><% @errors.each do |error|%>
		<li><%= error%></li>
	<%end%>
	</ul>
<%end%>

<%= render "form", :iguana => @iguana, :action => :edit%>

app/views/iguanas/index.html.erb
<h2>ALL THE IGUANAS!!!!1!</h2>

<ul>
	<% @iguanas.each do |ig|%>
	<li><%= link_to ig.name, iguana_url(ig) %></li>
	<% end %>
</ul>

<%= link_to "IGUANA CREATOR", new_iguana_url %>

app/views/iguanas/new.html.erb
<h2>MAKE AN IGUANA</h2>

<% unless @errors.nil?%>
	<ul><% @errors.each do |error|%>
		<li><%= error%></li>
	<%end%>
	</ul>
<%end%>

<% fake_iguana = Iguana.new() %>

<%= render "form", :iguana => fake_iguana, :action => :new%>

app/views/iguanas/show.html.erb
<h2>This is <%= @iguana.name.upcase %> the iguana</h2>


<h2>VITAL IGUANA DETAILS</h2>
<table>
	<tr>
		<th>Attribute</th>
		<th>VITAL INFORMATION</th>
	</tr>
	<tr>
		<td>Name</td>
		<td><%= @iguana.name.upcase %>
	</tr>
	<tr>
		<td>Age</td>
		<td><%= @iguana.age %>
	</tr>
	<tr>
		<td>Color</td>
		<td><%= @iguana.color.upcase %>
	</tr>
	<tr>
		<td>Sex</td>
		<td><%= @iguana.sex.upcase %>
	</tr>
	<tr>
		<td>Birthdate</td>
		<td><%= @iguana.birth_date %>
	</tr>
</table>

<h2>REQUESTS FOR THE IGUANA</h2>
<table>
	<tr>
		<th>IDENTIFICATION OF THE REQUEST</th>
		<th>DATE OF START</th>
		<th>DATE OF END</th>
		<th>DECISION OF THE IGUANA</th>
	</tr>
	<% @requests.each do |request| %>
	<tr>
		<td><%= request.id%></td>
		<td><%= request.start_date%></td>
		<td><%= request.end_date%></td>
		<td><%= request.status%></td>
		<% if request.status == "PENDING" && is_owner?%>
			<td><%= button_to "Approve",
				approve_iguana_house_cleaning_request_url(request), :method => :post %>
			</td>
			<td><%= button_to "Deny",
				deny_iguana_house_cleaning_request_url(request), :method => :post %>
			</td>
		<% end %>

	</tr>
	<% end %>
</table>

<%= link_to "EDIT THE IGUANA", edit_iguana_url(@iguana)%>